-- M10 · Reading-layer performance: two indexes, and nothing else (Phase 1 WP23)
--
-- WHAT THIS IS FOR. Every reading page was measured against production on
-- 15-16 September, loader by loader and read by read: Overview 9.9 s (Össur) /
-- 7.3 s (Sealand), This week 8.9 / 10.7, Market ~78 s once, and one statement
-- timeout in loadRecordInputs -> loadLanguage. Almost all of that was the
-- NUMBER of round trips and the order they were made in, and almost all of the
-- fix is in TypeScript — reads folded together, reads memoised for one request,
-- reads started when they stop depending on anything. `pg_stat_statements` says
-- the same thing from the database's side: the single most expensive statement
-- on this instance is PostgREST's own per-request `set_config(...)`, 80,938
-- calls for 155 s, which is the cost of ASKING, not of answering.
--
-- SO THIS FILE IS DELIBERATELY SMALL. An index goes in only where `explain
-- (analyze, buffers)` against production shows the plan is the problem. Two
-- did. Everything else the reading layer touches already has the index it
-- wants: `comments (client_id, comment_date)` exists, `comments_pkey` serves
-- the cited-comment reads (110 ms for a 100-id chunk),
-- `idx_insight_evidence_insight` serves the evidence reads (216 ms for 120
-- insights, a nested loop over the index), `month_denominators_pkey` and
-- `month_theme_readings_theme_idx` serve the month reads (10 ms and 34 ms), and
-- `config_changes_client_time_idx`, `pipeline_runs_client_id_idx` and
-- `videos_client_id_platform_video_id_key` serve the rest. Adding an index
-- there would cost write time on the gather path and buy nothing.
--
-- NOT `concurrently`. Both tables are small (videos 8,377 rows / 27 MB,
-- gate_verdicts 4,477 rows / 2.5 MB) so each build takes milliseconds, and a
-- CONCURRENTLY build cannot run inside the transaction a migration is applied
-- in. `if not exists` on both, so the file is idempotent and can be re-applied.

-- ============================================================================
-- 1 · videos — the record's corpus read, as an INDEX-ONLY scan
-- ============================================================================
--
-- lib/reading/record.ts reads every analysed non-Reddit video for two records:
-- how much of each video was read (speech / translation / on-screen text) and
-- what language it was spoken in. It is one read now rather than seven (five
-- `count: exact` head queries plus a paged read over the same population), and
-- the remaining one is the biggest read on the Overview.
--
-- WHAT IT COSTS TODAY, AND WHAT IT COSTS WITH THE INDEX. Three corpora, one
-- table, because the same read on the same shape of data gives different
-- numbers on different heaps and the difference IS the argument. The read is
-- the one loadCorpus issues (`order by id`, one 1,000-row page); "without" is
-- the plan the planner picks when this index is absent.
--
--   corpus                              row     rows in    without this index          with it
--                                       width   the read
--   ---------------------------------------------------------------------------------------------------------
--   production, 8,377 videos / 27 MB    3.3 KB   1,596     Index Scan on                (not applied here;
--   (explain analyze, read-only,                           videos_analyzed_run_idx,     the local clusters
--   16 September)                                          1,267 buffers, 886 ms        below stand in)
--
--   cluster A, 38,400 videos across     3.3 KB   3,491     Bitmap Heap Scan + sort,     Index Only Scan +
--   two tenants at production's                            1,512 heap blocks,           top-N sort,
--   width                                                  1,520 buffers                Heap Fetches 0,
--                                                                                       49 buffers
--
--   cluster B, 20,000 videos / 78 MB,   3.9 KB   4,571     Index Scan using             Index Only Scan +
--   transcripts INLINE (storage main,                      videos_pkey over the whole   top-N heapsort,
--   incompressible)                                        table, filtered,             Heap Fetches 0,
--                                                          4,443 buffers, 16.9 ms       62 buffers, 4.6 ms
--
--   cluster B, the SAME 20,000 rows     ~0.7 KB  4,571     Index Scan using             the planner did not
--   at 13 MB — a compressible                              videos_pkey,                 use this index at
--   transcript, so the text TOASTs                         4,286 buffers                all: 4,286 buffers
--   out of line
--
-- READ THE ROW WIDTH COLUMN, NOT THE ROW COUNT. Cluster B reports three times
-- cluster A's buffers on half the videos for two reasons that are both about
-- the heap and neither about the index: its rows are wider, and with no index
-- to bitmap the planner fell back to scanning `videos_pkey` over the whole
-- table instead of over the read's own population. The last row is the control
-- and the most useful line here: the same rows, the same read, a narrow heap —
-- and the index buys nothing, because there was never anything to save but
-- heap pages. THE DAY `videos` STOPS CARRYING ITS TRANSCRIPTS INLINE (a
-- transcript table, a storage change, a column moved), THIS INDEX STOPS PAYING
-- AND SHOULD BE DROPPED RATHER THAN CARRIED.
--
-- HEAP FETCHES: 0 IS THE BEST CASE, NOT THE CASE. An index-only scan skips the
-- heap only for pages the visibility map marks all-visible, and `videos` is
-- written constantly: by every gather, and — per video, all run long — by Pass
-- A's `updateBookkeeping`, which rewrites `analyzed_run_id` and all four
-- `analyzed_with_*` columns of this index in one statement. On cluster A, 200
-- videos re-stamped the way Pass A stamps them and no autovacuum since:
--
--   Heap Fetches: 736   788 buffers        (and back to 0 / 52 after a VACUUM)
--
-- So a production run leaves this scan partly reading the heap until autovacuum
-- catches up. It still wins — 788 buffers against the 1,520 of the scan with no
-- index at all, and 49 once the table settles — but the number to plan on is
-- the range, not the zero.
--
-- The key is `videos_analyzed_run_idx`'s plus `id`, and the INCLUDE columns are
-- the five the record selects. `platform` is among them because it is a FILTER
-- on this read, and a filter that sends the scan back to the heap is not an
-- index-only scan at all.
--
-- THE READ DOES NOT PAGE IN THIS INDEX'S ORDER, AND MUST NOT. loadCorpus orders
-- by `id` alone. `selectAll` fetches the population in 1,000-row ranges, and
-- what a range-paged read needs of its order key is not that it is unique but
-- that it cannot MOVE between pages — and `analyzed_run_id` is exactly the
-- column incremental Pass A rewrites one video at a time, while these pages are
-- expected to load with a run in flight. So the scan sorts, and the sort is
-- cheap: the index tuple is the whole answer, so the sort is over index tuples
-- and never opens the heap. `id` stays in the KEY rather than the payload
-- because that is what makes the tuple whole and the index unique.
--
-- THE COST IS ON THE WRITE SIDE, and the heavier half is not the gather: it is
-- that same Pass A bookkeeping, one index tuple per video analysed, on an index
-- whose key AND payload it writes. Plus ~500 KB of storage.
--
-- AND THERE IS AN OFFSET THAT IS NOT TAKEN HERE, BECAUSE IT IS NOT THIS FILE'S
-- TO TAKE. `videos_analyzed_run_idx (client_id, analyzed_run_id)` — from
-- 20260818090000_incremental_pass_a.sql — is a strict KEY PREFIX of the index
-- below, so once this one exists the old one answers no query this one cannot,
-- and every gather and every `updateBookkeeping` maintains both. Dropping it in
-- the same W1 window would give most of the write cost above straight back:
--
--   drop index if exists public.videos_analyzed_run_idx;   -- W1, deliberately, not here
--
-- It is left standing on purpose. A migration that creates an index for the
-- reading pages should not quietly remove one the pipeline has been planning
-- against since August, and the check is a person's: confirm nothing plans
-- `videos_analyzed_run_idx` by name and that this index is actually applied,
-- then drop it. It is on the deploy checklist beside this file.
create index if not exists videos_analysed_record_idx
  on public.videos (client_id, analyzed_run_id, id)
  include (platform, transcript_lang, analyzed_with_transcript, analyzed_with_translation, analyzed_with_ocr);

comment on index public.videos_analysed_record_idx is
  'Covering index for the record''s corpus read (lib/reading/record.ts loadCorpus): the five columns the read-depth and language records are computed from, carried as INCLUDE payload, so the scan is index-only. The read itself pages by `id`, which cannot move under it while Pass A stamps analyzed_run_id per video, so it sorts index tuples rather than opening the heap. Without this index the same read opens a heap page per row — 1,267 buffers for 1,596 rows on production — because a videos row averages 3.3 KB; the saving is the heap and nothing else, so it stops paying the day transcripts stop living inline. Phase 1 WP23.';

-- ============================================================================
-- 2 · gate_verdicts — the discard record's window, by time
-- ============================================================================
--
-- lib/reading/record.ts loadDiscard reads what the gate judged inside the
-- record's window. The five indexes gate_verdicts has all lead with
-- `client_id` and continue with `run_id` or `keyword`; none of them carries
-- `created_at`, and PostgreSQL 17 has no skip scan, so the window is a
-- sequential scan of the whole table:
--
--   Seq Scan on gate_verdicts
--     Filter: (created_at >= … AND created_at <= … AND client_id = …)
--     rows=2777  Rows Removed by Filter: 1700  Buffers: shared hit=213
--     actual time=235 ms
--
-- That was FIVE such scans until this package folded the five head counts into
-- one read; it is one now, and with this index it is an index scan over the
-- rows the window actually holds.
--
-- `created_at desc` rather than ascending, because the other read on this table
-- in the same loader is "when was the first verdict ever recorded" — a
-- `limit 1` on the ascending end, which this index serves backwards — and every
-- window a page asks for is a recent one.
create index if not exists gate_verdicts_client_time_idx
  on public.gate_verdicts (client_id, created_at desc);

comment on index public.gate_verdicts_client_time_idx is
  'The discard record''s window read (lib/reading/record.ts loadDiscard) filters client_id and a created_at range; no other index on this table carries created_at, so the window was a full sequential scan. Phase 1 WP23.';
